import { describe, it, beforeEach, vi } from 'vitest';
import {
  newGrooveWriter,
  buildGridDOM,
  shimCrossModuleConstants,
} from '../helpers/loadGrooveWriter.js';
import { buildNoteMenusHTML } from '../../js/viewHtml.js';
import { expectGolden } from '../helpers/golden.js';

// Characterization of every note / label context-menu action plus the left-click
// and ctrl/alt mouse-enter paths. The menu markup (generated by
// buildNoteMenusHTML; it used to be hand-written in index.html) is parsed back
// here, so these goldens also guard that markup.

const html = buildNoteMenusHTML();
const INSTRUMENTS = ['sticking', 'hh', 'tom1', 'tom4', 'snare', 'kick'];

function parseMenus() {
  const doc = new DOMParser().parseFromString(html, 'text/html');
  const out = {};
  for (const ul of doc.querySelectorAll('.noteContextMenu ul')) {
    if (!/^(sticking|stickings|hh|tom1|tom4|snare|kick)(Label)?ContextMenu$/.test(ul.id)) continue;
    out[ul.id] = [...ul.querySelectorAll('li')].map((li) => ({
      id: li.id || null,
      onclick: li.getAttribute('onclick').replace(/,\s+/g, ','),
      text: li.textContent,
    }));
  }
  return out;
}

function parseCall(onclick) {
  const m = /myGrooveWriter\.(\w+)\((.*)\);?$/.exec(onclick.trim());
  return { fn: m[1], args: JSON.parse('[' + m[2].replace(/'/g, '"') + ']') };
}

let gw;
let noteOn;

function snapshot() {
  const gd = gw.grooveDataFromClickableUI();
  return {
    hh: gd.hh_array,
    snare: gd.snare_array,
    kick: gd.kick_array,
    toms: gd.toms_array,
    sticking: gd.sticking_array,
    sounds: noteOn.mock.calls.map((c) => c.slice(0, 3)),
  };
}

function reset() {
  for (const inst of ['stickings', 'hh', 'tom1', 'tom4', 'snare', 'kick']) {
    for (const m of [1]) {
      gw.noteLabelClick({}, inst, m);
      gw.noteLabelPopupClick(inst, 'all_off');
    }
  }
  for (const [i, state] of [
    [0, 'normal'],
    [3, 'normal'],
    [6, 'splash'],
    [9, 'kick_and_splash'],
  ]) {
    gw.noteRightClick({}, 'kick', i);
    gw.notePopupClick('kick', state);
  }
  noteOn.mockClear();
}

beforeEach(async () => {
  document.body.innerHTML = '';
  shimCrossModuleConstants();
  noteOn = vi.fn();
  globalThis.MIDI = { WebAudio: { noteOn }, AudioTag: { noteOn } };
  gw = await newGrooveWriter();
  buildGridDOM(gw, 2);
  const extra = document.createElement('div');
  extra.innerHTML =
    '<textarea id="ABCsource"></textarea><div id="svgTarget"></div><div id="diverr"></div>';
  document.body.appendChild(extra);
  for (const [id, items] of Object.entries(parseMenus())) {
    const ul = document.createElement('ul');
    ul.id = id;
    for (const it of items) {
      const li = document.createElement('li');
      if (it.id) li.id = it.id;
      ul.appendChild(li);
    }
    document.body.appendChild(ul);
  }
  gw.refresh_ABC = vi.fn();
  gw.updateCurrentURL = vi.fn();
  gw.displayNewSVG = vi.fn();
  gw.stickingsShowHide(true, true, true);
  gw.showHideToms(true, true, true);
  window.myGrooveWriter = gw;
});

describe('note interactions (golden)', () => {
  it('menu markup', () => {
    expectGolden('note-menu-markup.json', parseMenus());
  });

  it('every menu item action', () => {
    const result = {};
    for (const [menuId, items] of Object.entries(parseMenus())) {
      items.forEach((item, idx) => {
        reset();
        const { fn, args } = parseCall(item.onclick);
        const measure = menuId.includes('Label') ? 1 : null;
        if (fn === 'notePopupClick') {
          gw.noteRightClick({ clientX: 100, clientY: 100 }, args[0], 5);
        } else {
          gw.noteLabelClick({ clientX: 100, clientY: 100 }, args[0], measure);
        }
        const ul = document.getElementById(menuId);
        const shown = { top: ul.style.top, left: ul.style.left };
        gw[fn](...args);
        result[`${menuId}#${idx}`] = { call: [fn, ...args], shown, ...snapshot() };
      });
    }
    expectGolden('note-menu-actions.json', result);
  }, 120000);

  it('menu display on right-click / label-click, incl. bad type', () => {
    const result = {};
    for (const inst of [...INSTRUMENTS, 'bogus']) {
      const ev = { clientX: 200, clientY: 300 };
      result['right_' + inst] = [gw.noteRightClick(ev, inst, 3)];
      result['label_' + inst] = [
        gw.noteLabelClick(ev, inst === 'sticking' ? 'stickings' : inst, 1),
      ];
      result['menus_' + inst] = [...document.querySelectorAll('ul[id$=ContextMenu]')]
        .filter((u) => u.style.top)
        .map((u) => [u.id, u.style.top, u.style.left]);
    }
    expectGolden('note-menu-display.json', result);
  });

  it('left-click cycles and ctrl/alt mouse-enter', () => {
    const result = {};
    for (const inst of INSTRUMENTS) {
      for (let i = 0; i < 6; i++) {
        gw.noteLeftClick({}, inst, 2);
        result[`left_${inst}_${i}`] = snapshot();
      }
      for (const [k, ev] of [
        ['ctrl', { ctrlKey: true }],
        ['alt', { altKey: true }],
        ['none', {}],
      ]) {
        gw.noteOnMouseEnter(ev, inst, 4);
        result[`enter_${inst}_${k}`] = snapshot();
      }
    }
    gw.noteOnMouseEnter({ ctrlKey: true }, 'bogus', 4);
    gw.noteLeftClick({}, 'bogus', 4);
    expectGolden('note-click-cycles.json', result);
  });
});
