import { vi } from 'vitest';

// Helpers for testing js/groove_writer.js (the GrooveWriter authoring UI).
//
// groove_writer.js is now an ES module that imports GrooveUtils and the shared
// constants directly from groove_utils.js, so tests just import it — no global
// shims needed. Because GrooveWriter keeps per-instance state in module/closure
// scope and the ES module is cached, we vi.resetModules() per construction for
// isolation.

/**
 * Construct a fresh GrooveWriter.
 * @returns {Promise<object>} a `new GrooveWriter()` instance.
 */
export async function newGrooveWriter() {
  vi.resetModules();
  const { GrooveWriter } = await import('../../js/groove_writer.js');
  return new GrooveWriter();
}

/**
 * Build the minimal DOM the clickable authoring grid needs: the staff container
 * markup (generated by the writer itself) plus the tune-metadata inputs that
 * grooveDataFromClickableUI reads. Append everything to document.body.
 *
 * @param {object} gw a GrooveWriter instance
 * @param {number} [measures] how many measures of grid to render (default 1)
 * @returns {HTMLElement} the container element holding the grid
 */
export function buildGridDOM(gw, measures = 1) {
  // The writer rebuilds the grid by writing into #measureContainer (e.g. on
  // division/measure changes), so the grid must live inside that element.
  const container = document.createElement('div');
  container.id = 'measureContainer';
  let html = '';
  for (let m = 1; m <= measures; m++) {
    html += gw.HTMLforStaffContainer(m, (m - 1) * gw.notesPerMeasure());
  }
  container.innerHTML = html;
  document.body.appendChild(container);

  // Metadata inputs read by grooveDataFromClickableUI / updateCurrentURL.
  const inputs = document.createElement('div');
  inputs.innerHTML =
    '<input id="tuneTitle" value=""><input id="tuneAuthor" value="">' +
    '<input id="tuneComments" value=""><input id="showLegend" type="checkbox">';
  document.body.appendChild(inputs);

  return container;
}

/**
 * Build the fuller page DOM that the load/render pipeline needs
 * (set_Default_notes / loadNewGroove / updateSheetMusic / displayNewSVG /
 * setMetronomeFrequency), on top of buildGridDOM. The SVG render is stubbed so
 * abc2svg is not required; the rest is real.
 *
 * @param {object} gw a GrooveWriter instance
 * @param {number} [measures] measures of grid to render (default 1)
 * @returns {HTMLElement} the grid container
 */
export function buildFullPageDOM(gw, measures = 1) {
  const container = buildGridDOM(gw, measures);

  // GrooveUtils tempo/swing setters write to inputs suffixed with the instance's
  // unique index; set_Default_notes calls setTempo/setSwing.
  const idx = gw.myGrooveUtils.grooveUtilsUniqueIndex;
  const extra = document.createElement('div');
  // Subdivision buttons highlighted on a division change.
  const subdivisions = [4, 8, 12, 16, 24, 32, 48]
    .map((d) => `<div id="subdivision_${d}ths"></div>`)
    .join('');
  extra.innerHTML =
    '<div id="svgTarget"></div><div id="diverr"></div><textarea id="ABCsource"></textarea>' +
    '<div id="GrooveDB_source"></div><div id="PermutationOptions"></div><div id="midiPlayer"></div>' +
    '<div id="metronomeOff"></div><div id="metronome4ths"></div>' +
    '<div id="metronome8ths"></div><div id="metronome16ths"></div>' +
    '<div id="timeSigLabel"></div>' +
    subdivisions +
    `<input id="tempoInput${idx}"><span id="tempoTextField${idx}"></span>` +
    `<input id="swingInput${idx}"><span id="swingOutput${idx}"></span>`;
  document.body.appendChild(extra);

  // Avoid pulling in abc2svg: stub the SVG renderer the writer calls.
  gw.myGrooveUtils.renderABCtoSVG = () => ({ svg: '<svg data-stub="1"></svg>', error_html: '' });

  return container;
}

// groove_writer.js is written assuming classic <script> global-scope sharing
// with groove_utils.js: it has a top-of-file `/*global ... */` comment listing
// bare identifiers (constant_ABC_*, constant_OUR_MIDI_*) that it expects to
// find on the page's shared global scope because, in the real app, both files
// are plain <script> tags whose top-level `var`s all land on `window`.
//
// Vitest's transform plugin (see vitest.config.js) turns each legacy file into
// its own real ES module so it can be `import`ed -- but that means groove_writer.js
// no longer shares scope with groove_utils.js: its module-level `var`s (the
// note-on/off color constants, which groove_writer.js *does* redeclare locally)
// resolve fine, but the ABC-notation and MIDI-note-number constants that only
// groove_utils.js declares are simply undefined here, and any code path that
// reads them throws a ReferenceError. We shim them onto globalThis with the
// literal values copied from groove_utils.js so the note-state getters/setters
// (which are otherwise being tested faithfully, unmodified) can run.
export function shimCrossModuleConstants() {
  globalThis.constant_ABC_STICK_R = '"R"x';
  globalThis.constant_ABC_STICK_L = '"L"x';
  globalThis.constant_ABC_STICK_BOTH = '"R/L"x';
  globalThis.constant_ABC_STICK_COUNT = '"count"x';
  globalThis.constant_ABC_STICK_OFF = '""x';
  globalThis.constant_ABC_HH_Ride = "^A'";
  globalThis.constant_ABC_HH_Ride_Bell = "^B'";
  globalThis.constant_ABC_HH_Cow_Bell = "^D'";
  globalThis.constant_ABC_HH_Crash = "^c'";
  globalThis.constant_ABC_HH_Stacker = "^d'";
  globalThis.constant_ABC_HH_Metronome_Normal = "^e'";
  globalThis.constant_ABC_HH_Metronome_Accent = "^f'";
  globalThis.constant_ABC_HH_Open = '!open!^g';
  globalThis.constant_ABC_HH_Close = '!plus!^g';
  globalThis.constant_ABC_HH_Accent = '!accent!^g';
  globalThis.constant_ABC_HH_Normal = '^g';
  globalThis.constant_ABC_SN_Ghost = '!(.!!).!c';
  globalThis.constant_ABC_SN_Accent = '!accent!c';
  globalThis.constant_ABC_SN_Normal = 'c';
  globalThis.constant_ABC_SN_XStick = '^c';
  globalThis.constant_ABC_SN_Buzz = '!///!c';
  globalThis.constant_ABC_SN_Flam = '!accent!{/c}c';
  globalThis.constant_ABC_SN_Drag = '{/cc}c';
  globalThis.constant_ABC_KI_SandK = '[F^d,]';
  globalThis.constant_ABC_KI_Splash = '^d,';
  globalThis.constant_ABC_KI_Normal = 'F';
  globalThis.constant_ABC_T1_Normal = 'e';
  globalThis.constant_ABC_T2_Normal = 'd';
  globalThis.constant_ABC_T3_Normal = 'B';
  globalThis.constant_ABC_T4_Normal = 'A';
  globalThis.constant_NUMBER_OF_TOMS = 4;
  globalThis.constant_ABC_OFF = false;
  globalThis.constant_OUR_MIDI_VELOCITY_NORMAL = 85;
  globalThis.constant_OUR_MIDI_VELOCITY_ACCENT = 120;
  globalThis.constant_OUR_MIDI_VELOCITY_GHOST = 50;
  globalThis.constant_OUR_MIDI_METRONOME_1 = 76;
  globalThis.constant_OUR_MIDI_METRONOME_NORMAL = 77;
  globalThis.constant_OUR_MIDI_HIHAT_NORMAL = 42;
  globalThis.constant_OUR_MIDI_HIHAT_OPEN = 46;
  globalThis.constant_OUR_MIDI_HIHAT_ACCENT = 108;
  globalThis.constant_OUR_MIDI_HIHAT_CRASH = 49;
  globalThis.constant_OUR_MIDI_HIHAT_STACKER = 52;
  globalThis.constant_OUR_MIDI_HIHAT_METRONOME_NORMAL = 77;
  globalThis.constant_OUR_MIDI_HIHAT_METRONOME_ACCENT = 76;
  globalThis.constant_OUR_MIDI_HIHAT_RIDE = 51;
  globalThis.constant_OUR_MIDI_HIHAT_RIDE_BELL = 53;
  globalThis.constant_OUR_MIDI_HIHAT_COW_BELL = 105;
  globalThis.constant_OUR_MIDI_HIHAT_FOOT = 44;
  globalThis.constant_OUR_MIDI_SNARE_NORMAL = 38;
  globalThis.constant_OUR_MIDI_SNARE_ACCENT = 22;
  globalThis.constant_OUR_MIDI_SNARE_GHOST = 21;
  globalThis.constant_OUR_MIDI_SNARE_XSTICK = 37;
  globalThis.constant_OUR_MIDI_SNARE_BUZZ = 104;
  globalThis.constant_OUR_MIDI_SNARE_FLAM = 107;
  globalThis.constant_OUR_MIDI_SNARE_DRAG = 103;
  globalThis.constant_OUR_MIDI_KICK_NORMAL = 35;
  globalThis.constant_OUR_MIDI_TOM1_NORMAL = 48;
  globalThis.constant_OUR_MIDI_TOM2_NORMAL = 47;
  globalThis.constant_OUR_MIDI_TOM3_NORMAL = 45;
  globalThis.constant_OUR_MIDI_TOM4_NORMAL = 43;
}
