import { vi } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Helpers for testing js/groove_writer.js (the GrooveWriter authoring UI).
//
// GrooveWriter is a global-scoped constructor (like GrooveUtils) that the
// transform plugin re-exports. Its constructor does `new GrooveUtils()`, so the
// real GrooveUtils must be present on globalThis before construction.
//
// IMPORTANT — cross-file globals: groove_writer.js references ~60 bare
// identifiers (constant_ABC_*, constant_OUR_MIDI_*, constant_NUMBER_OF_TOMS, …)
// that are declared as top-level `var`s in groove_utils.js. In the real app both
// files load as classic <script>s sharing one window, so those are ambient
// globals. Under Vitest's per-file ESM transform each file is its own module
// scope, so groove_writer can't see them and any note-setting path throws
// ReferenceError. installGrooveUtilsGlobals() reproduces the browser's shared
// global scope by evaluating groove_utils.js at global scope (indirect eval, in
// non-strict mode) so its top-level `var`s become globalThis properties -- with
// the REAL production values, not hand-copied literals. groove_writer.js is
// still `import`ed (so V8 coverage tracks it); only the shared constants come
// from the eval.
//
// Because GrooveWriter keeps per-instance state in module/closure scope and the
// ES module is cached, we vi.resetModules() per construction for isolation.

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GROOVE_UTILS_SRC = path.resolve(__dirname, '../../js/groove_utils.js');

/**
 * Populate globalThis with groove_utils.js's top-level globals (constants +
 * GrooveUtils), reproducing the browser's shared classic-script scope.
 * @returns {object} the GrooveUtils constructor now available on globalThis.
 */
export function installGrooveUtilsGlobals() {
  const src = fs.readFileSync(GROOVE_UTILS_SRC, 'utf8');
  // Indirect eval runs `src` in the global scope; its non-strict top-level
  // `var`/`function` declarations become properties of globalThis.
  (0, eval)(src);
  return globalThis.GrooveUtils;
}

/**
 * Construct a fresh GrooveWriter with the real GrooveUtils + shared constants
 * installed globally.
 * @returns {Promise<object>} a `new GrooveWriter()` instance.
 */
export async function newGrooveWriter() {
  vi.resetModules();
  installGrooveUtilsGlobals();
  // Import the module too, so GrooveUtils methods invoked by the writer are the
  // coverage-tracked module instances rather than the eval'd copy.
  const { GrooveUtils } = await import('../../js/groove_utils.js');
  globalThis.GrooveUtils = GrooveUtils;
  const { GrooveWriter } = await import('../../js/groove_writer.js');
  return new GrooveWriter();
}

/**
 * Build the minimal DOM the clickable authoring grid needs: the staff container
 * markup (generated by the writer itself) plus the tune-metadata inputs that
 * grooveDataFromClickableUI reads. Append everything to document.body.
 *
 * @param {object} gw a GrooveWriter instance
 * @param {number} [measures] how many measures of grid to render (default 1)
 * @returns {HTMLElement} the container element holding the grid
 */
export function buildGridDOM(gw, measures = 1) {
  // The writer rebuilds the grid by writing into #measureContainer (e.g. on
  // division/measure changes), so the grid must live inside that element.
  const container = document.createElement('div');
  container.id = 'measureContainer';
  let html = '';
  for (let m = 1; m <= measures; m++) {
    html += gw.HTMLforStaffContainer(m, (m - 1) * gw.notesPerMeasure());
  }
  container.innerHTML = html;
  document.body.appendChild(container);

  // Metadata inputs read by grooveDataFromClickableUI / updateCurrentURL.
  const inputs = document.createElement('div');
  inputs.innerHTML =
    '<input id="tuneTitle" value=""><input id="tuneAuthor" value="">' +
    '<input id="tuneComments" value=""><input id="showLegend" type="checkbox">';
  document.body.appendChild(inputs);

  return container;
}

/**
 * Build the fuller page DOM that the load/render pipeline needs
 * (set_Default_notes / loadNewGroove / updateSheetMusic / displayNewSVG /
 * setMetronomeFrequency), on top of buildGridDOM. The SVG render is stubbed so
 * abc2svg is not required; the rest is real.
 *
 * @param {object} gw a GrooveWriter instance
 * @param {number} [measures] measures of grid to render (default 1)
 * @returns {HTMLElement} the grid container
 */
export function buildFullPageDOM(gw, measures = 1) {
  const container = buildGridDOM(gw, measures);

  // GrooveUtils tempo/swing setters write to inputs suffixed with the instance's
  // unique index; set_Default_notes calls setTempo/setSwing.
  const idx = gw.myGrooveUtils.grooveUtilsUniqueIndex;
  const extra = document.createElement('div');
  // Subdivision buttons highlighted on a division change.
  const subdivisions = [4, 8, 12, 16, 24, 32, 48]
    .map((d) => `<div id="subdivision_${d}ths"></div>`)
    .join('');
  extra.innerHTML =
    '<div id="svgTarget"></div><div id="diverr"></div><textarea id="ABCsource"></textarea>' +
    '<div id="GrooveDB_source"></div><div id="PermutationOptions"></div><div id="midiPlayer"></div>' +
    '<div id="metronomeOff"></div><div id="metronome4ths"></div>' +
    '<div id="metronome8ths"></div><div id="metronome16ths"></div>' +
    '<div id="timeSigLabel"></div>' +
    subdivisions +
    `<input id="tempoInput${idx}"><span id="tempoTextField${idx}"></span>` +
    `<input id="swingInput${idx}"><span id="swingOutput${idx}"></span>`;
  document.body.appendChild(extra);

  // Avoid pulling in abc2svg: stub the SVG renderer the writer calls.
  gw.myGrooveUtils.renderABCtoSVG = () => ({ svg: '<svg data-stub="1"></svg>', error_html: '' });

  return container;
}
