/**
 * Centralized drum pad identifiers to avoid literal string duplication
 */
export const DrumType = {
    KICK: 'kick',
    SNARE: 'snare',
    SNARE_GHOST: 'snare_ghost',
    SNARE_XSTICK: 'snare_xstick',
    SNARE_FLAM: 'snare_flam',
    SNARE_BUZZ: 'snare_buzz',
    SNARE_ACCENT: 'snare_accent',

    HH_CLOSED: 'hh_closed',
    HH_FOOT: 'hh_foot',
    HH_OPEN: 'hh_open',
    HH_ACCENT: 'hh_accent',

    TOM_HIGH: 'tom_high',
    TOM_LOW: 'tom_low',

    CRASH: 'crash',
    RIDE: 'ride',
    RIDE_BELL: 'ride_bell',
    COWBELL: 'cow_bell',
    STACKER: 'stacker',

    METRONOME_NORMAL: 'metronome_normal',
    METRONOME_ACCENT: 'metronome_accent',

    // Virtual types for rendering/engine
    FLAM_GRACE: 'flam_grace',
    UNKNOWN: 'unknown'
};

/**
 * List of drum types that can be generated by a drum module or hardware.
 * Performances and MIDI files should only contains hits of these types.
 */
export const ModuleDrumTypes = [
    DrumType.KICK,
    DrumType.SNARE,
    DrumType.SNARE_XSTICK,
    DrumType.HH_FOOT,
    DrumType.HH_OPEN,
    DrumType.HH_CLOSED,
    DrumType.TOM_HIGH,
    DrumType.TOM_LOW,
    DrumType.CRASH,
    DrumType.RIDE,
    DrumType.RIDE_BELL,
    DrumType.COWBELL,
    DrumType.STACKER,
];


/**
 * Mapping from Editor drum types (articulations) to base Module drum types.
 * Allows the engine to match specific notations (e.g. snare_ghost) 
 * against standard trigger inputs (e.g. snare).
 */
export const EditorDrumToModuleDrum = {
    [DrumType.KICK]: DrumType.KICK,
    [DrumType.SNARE]: DrumType.SNARE,
    [DrumType.SNARE_GHOST]: DrumType.SNARE,
    [DrumType.SNARE_XSTICK]: DrumType.SNARE,
    [DrumType.SNARE_FLAM]: DrumType.SNARE,
    [DrumType.FLAM_GRACE]: DrumType.SNARE,
    [DrumType.SNARE_BUZZ]: DrumType.SNARE, // This should be implemented properly
    [DrumType.SNARE_ACCENT]: DrumType.SNARE,
    [DrumType.HH_CLOSED]: DrumType.HH_CLOSED,
    [DrumType.HH_FOOT]: DrumType.HH_FOOT,
    [DrumType.HH_OPEN]: DrumType.HH_OPEN,
    [DrumType.HH_ACCENT]: DrumType.HH_CLOSED,
    [DrumType.TOM_HIGH]: DrumType.TOM_HIGH,
    [DrumType.TOM_LOW]: DrumType.TOM_LOW,
    [DrumType.CRASH]: DrumType.CRASH,
    [DrumType.RIDE]: DrumType.RIDE,
    [DrumType.RIDE_BELL]: DrumType.RIDE_BELL,
    [DrumType.COWBELL]: DrumType.COWBELL,
    [DrumType.STACKER]: DrumType.STACKER
};

/**
 * List of drum types supported by the editor notation grid.
 */
export const EditorDrumTypes = [
    DrumType.KICK,
    DrumType.SNARE,
    DrumType.SNARE_GHOST,
    DrumType.SNARE_XSTICK,
    DrumType.SNARE_FLAM,
    DrumType.SNARE_BUZZ,
    DrumType.SNARE_ACCENT,
    DrumType.HH_CLOSED,
    DrumType.HH_FOOT,
    DrumType.HH_OPEN,
    DrumType.HH_ACCENT,
    DrumType.TOM_HIGH,
    DrumType.TOM_LOW,
    DrumType.CRASH,
    DrumType.RIDE,
    DrumType.RIDE_BELL,
    DrumType.COWBELL,
    DrumType.STACKER,
    DrumType.METRONOME_NORMAL,
    DrumType.METRONOME_ACCENT
];

/**
 * Mapping from ABC notation pitch strings to DrumType.
 *
 * grooveDataFromClickableUI() returns raw ABC notation in its arrays
 * (e.g. "^c'" for crash, "!open!^g" for open hi-hat). Consumers must
 * strip decorations (!open!, !accent!, etc.) before looking up the pitch.
 *
 * Each pitch corresponds to a %%map entry in groove_utils.js:
 *   %%map drummap ^g  print=g  heads=x_head  ...
 *   %%map drummap ^c' print=c' heads=x_head  ...
 */
export const ABC_PITCH_TO_DRUM_TYPE = {
    // Hi-hat / cymbals
    "^g": DrumType.HH_CLOSED,
    "^A'": DrumType.RIDE,
    "^B'": DrumType.RIDE_BELL,
    "^c'": DrumType.CRASH,
    "^d'": DrumType.STACKER,
    "^D'": DrumType.COWBELL,

    // Metronome
    "^e'": DrumType.METRONOME_NORMAL,
    "^f'": DrumType.METRONOME_ACCENT,

    // Snare
    "c": DrumType.SNARE,
    "^c": DrumType.SNARE_XSTICK,

    // Kick / Feet
    "F": DrumType.KICK,
    "^d,": DrumType.HH_FOOT,

    // Toms
    "e": DrumType.TOM_HIGH,
    "A": DrumType.TOM_LOW,
};
